lvm: fix backtrace when vg/lv is inactive or broken
When lv/vg is inactive/broken and we have a lvm snapshot, it's possible to
end up crashing because 'snap_size' may not be defined:

size = float(snap['vol_size']) * float(snap['snap_size'])
ValueError: could not convert string to float:

Fix this be removing the snap_size field altogether. Add tests.

Signed-off-by: Lukas Czerner <lczerner@redhat.com>
Reviewed-by: Jan Tulak <jtulak@redhat.com>